spring.datasource.url=jdbc:postgresql://localhost:5432/imoblink_db
spring.datasource.username=imoblink
spring.datasource.password=imoblink

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

upload.dir=uploads

logging.level.org.springframework.security=DEBUG