spring.datasource.url=${DB_URL}
spring.datasource.username=${APP_DB_USER}
spring.datasource.password=${APP_DB_PASSWORD}

spring.flyway.url=${DB_URL}
spring.flyway.user=${MIGRATOR_DB_USER}
spring.flyway.password=${MIGRATOR_DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false

#jwt.secret=${JWT_SECRET}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

#storage.bucket=${STORAGE_BUCKET}
#storage.region=${STORAGE_REGION}
#storage.access-key=${STORAGE_ACCESS_KEY}
#storage.secret-key=${STORAGE_SECRET_KEY}
#storage.endpoint=${STORAGE_ENDPOINT}

logging.level.org.springframework.security=WARN

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never