# application-test.properties

spring.application.name=imoblink

# Banco (vamos ajustar depois)
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# Hibernate
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true

# SQL apenas se precisar depurar
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true