spring.application.name=ImobLink

spring.datasource.url=jdbc:postgresql://localhost:5432/imoblink_db
spring.datasource.username=imoblink
spring.datasource.password=imoblink
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Arquivos de upload
upload.dir=uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=200MB