spring.datasource.url=${DB_URL}

spring.datasource.username=${APP_DB_USER}
spring.datasource.password=${APP_DB_PASSWORD}

spring.flyway.user=${MIGRATOR_DB_USER}
spring.flyway.password=${MIGRATOR_DB_PASSWORD}

jwt.secret=${JWT_SECRET}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

upload.dir=uploads

logging.level.org.springframework.security=DEBUG