spring.datasource.url=jdbc:postgresql://localhost:5432/imoblink_db

spring.datasource.username=imoblink_app
spring.datasource.password=${APP_DB_PASSWORD}

spring.flyway.user=imoblink_migrator
spring.flyway.password=${MIGRATOR_DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

upload.dir=uploads

logging.level.org.springframework.security=DEBUG